export const s = {
  header:     { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  titulo:     { fontSize: '24px', fontWeight: '700', color: '#f1f5f9', marginBottom: '4px' },
  sub:         { fontSize: '14px', color: '#64748b' },
  controles:  { display: 'flex', alignItems: 'flex-end', gap: '24px', marginBottom: '16px' },
  label:      { display: 'block', fontSize: '13px', color: '#94a3b8', marginBottom: '6px' },
  inputFecha: { padding: '9px 12px', background: '#13151f', border: '1px solid #1e2130', borderRadius: '8px', color: '#e2e8f0', fontSize: '14px', outline: 'none' },
  stats:      { display: 'flex', gap: '12px' },
  stat:       { background: '#13151f', border: '1px solid', borderRadius: '10px', padding: '10px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2px', minWidth: '80px' },
  statLabel:  { fontSize: '12px', color: '#64748b' },
  accBtns:    { display: 'flex', gap: '8px', marginBottom: '16px' },
  btnSec:     { padding: '8px 14px', background: '#1e2130', border: '1px solid #334155', borderRadius: '8px', color: '#94a3b8', fontSize: '13px', cursor: 'pointer' },
  tabla:      { background: '#13151f', border: '1px solid #1e2130', borderRadius: '12px', overflow: 'hidden' },
  table:      { width: '100%', borderCollapse: 'collapse' },
  th:         { padding: '12px 16px', textAlign: 'left', fontSize: '12px', color: '#64748b', textTransform: 'uppercase', borderBottom: '1px solid #1e2130' },
  tr:         { borderBottom: '1px solid #1e2130' },
  td:         { padding: '12px 16px', fontSize: '14px', color: '#cbd5e1', verticalAlign: 'middle' },
  tdCenter:   { padding: '32px', textAlign: 'center', color: '#475569', fontSize: '14px' },
  nombre:     { fontWeight: '600', color: '#f1f5f9' },
  cinta:      { fontSize: '12px', color: '#94a3b8', textTransform: 'capitalize' },
  toggleBtn:  { padding: '6px 16px', borderRadius: '20px', border: '1px solid', fontSize: '13px', fontWeight: '600', cursor: 'pointer', minWidth: '110px' },
  btnPrimary: { background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 18px', fontSize: '14px', cursor: 'pointer', fontWeight: '600' },
}