/*const s = {
  statusActivoBg: '#14532d',
  statusActivoText: '#4ade80',
  statusInactivoBg: '#450a0a',
  statusInactivoText: '#f87171',

  container: { scrollbarGutter: 'stable', paddingBottom: '40px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  titulo: { fontSize: '24px', fontWeight: '700', color: '#f1f5f9' },
  sub: { fontSize: '15px', color: '#64748b', marginTop: '2px' },
  barraAcciones: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '20px', marginBottom: '16px' },
  search: { flex: 1, maxWidth: '395px', padding: '10px 16px', background: '#13151f', border: '1px solid #1e2130', borderRadius: '80px', color: '#e2e8f0', outline: 'none', transition: 'all 0.3s ease' },
  tabs: { display: 'flex', background: '#13151f', padding: '4px', borderRadius: '10px', border: '1px solid #1e2130', flexShrink: 0 },
  tab: { padding: '8px 16px', background: 'transparent', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: '13px', minWidth: '120px', textAlign: 'center' },
  tabActiveVerde: { padding: '8px 16px', background: '#14532d', border: 'none', color: '#4ade80', borderRadius: '8px', fontWeight: '600', fontSize: '13px', minWidth: '120px', textAlign: 'center' },
  tabActiveRojo: { padding: '8px 16px', background: '#450a0a', border: 'none', color: '#f87171', borderRadius: '8px', fontWeight: '600', fontSize: '13px', minWidth: '120px', textAlign: 'center' },
  tabActiveAzul: { padding: '8px 16px', background: '#1e3a8a', border: 'none', color: '#60a5fa', borderRadius: '8px', fontWeight: '600', fontSize: '13px', minWidth: '120px', textAlign: 'center' },
  filtrosSecundarios: { display: 'flex', justifyContent: 'space-between', marginBottom: '16px', alignItems: 'center', flexWrap: 'wrap', gap: '12px' },
  selectFiltro: { padding: '8px 8px', background: '#0f1117', border: '1px solid #1e2130', borderRadius: '8px', color: '#cbd5e1', outline: 'none', fontSize: '13px', cursor: 'pointer', minWidth: '140px' },
  btnLimpiarWrapper: { display: 'inline-block', width: '90px' },
  btnLimpiar: { width: '100%', padding: '8px 10px', background: '#1e2130', border: '1px solid #334155', color: '#cbd5e1', borderRadius: '8px', cursor: 'pointer', fontSize: '12px', fontWeight: '600' },
  btnExportExcel: { background: '#linear-gradient(135deg, #10b981 0%, #059669 100%)', color: '#fff', border: 'none', borderRadius: '8px', padding: '8px 12px', fontSize: '12px', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', transition: 'all 0.2s', whiteSpace: 'nowrap', boxShadow: '0 4px 15px rgba(16, 185, 129, 0.3)', },
  btnExportPdf: { background: '#991b1b', color: '#fff', border: 'none', borderRadius: '8px', padding: '8px 12px', fontSize: '12px', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', transition: 'all 0.2s', whiteSpace: 'nowrap' },
  tabla: { background: '#13151f', borderRadius: '12px', border: '1px solid #1e2130', overflow: 'hidden', minHeight: '400px' },
  tablaScroll: { width: '100%', overflowX: 'auto', overflowY: 'hidden' },
  table: { width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed', minWidth: '1000px' },
  th: { padding: '10px 16px', textAlign: 'center', fontSize: '12px', color: '#64748b', borderBottom: '1px solid #1e2130', textTransform: 'uppercase', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', },
  td: { padding: '10px 16px', fontSize: '14px', color: '#cbd5e1', verticalAlign: 'middle', textAlign: 'center', whiteSpace: 'nowrap', overflow: 'hidden', },
  tdCenter: { padding: '32px', textAlign: 'center', color: '#475569' },
  fotoTabla: { width: '40px', height: '40px', borderRadius: '50%', objectFit: 'cover', border: '2px solid #1e2130' },
  fotoVacia: { width: '40px', height: '40px', borderRadius: '50%', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', fontWeight: '700', color: '#60a5fa' },
  nombreNom: { fontWeight: '600', color: '#f1f5f9', overflow: 'hidden', textOverflow: 'ellipsis' },
  emailSub: { fontSize: '12px', color: '#94a3b8', marginTop: '2px' },
  cinta: { padding: '5px 12px', borderRadius: '20px', fontSize: '13px', fontWeight: '600', display: 'inline-block', minWidth: '100px' },
  badge: { padding: '5px 12px', borderRadius: '20px', fontSize: '13px', fontWeight: '600', },
  acciones: { display: 'flex', gap: '6px', justifyContent: 'center', alignItems: 'center' },
  btnVer: { background: '#0f172a', border: '1px solid #1e2130', borderRadius: '6px', padding: '5px 5px', cursor: 'pointer', color: '#94a3b8', fontSize: '12px' },
  btnEdit: { background: '#1e2d4a', border: 'none', borderRadius: '6px', padding: '5px 5px', cursor: 'pointer', color: '#60a5fa', fontSize: '12px' },
  btnDel: { background: '#2d1515', border: 'none', borderRadius: '6px', padding: '5px 5px', cursor: 'pointer', color: '#f87171', fontSize: '12px' },
  btnNuevoAlumno: { background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)', color: '#fff', border: 'none', borderRadius: '10px', padding: '10px 20px', fontWeight: '600', cursor: 'pointer', boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)', transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '6px' },
  btnPrimary: { background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 18px', fontWeight: '600', cursor: 'pointer' },
  btnSecondary: { background: '#1e2130', color: '#94a3b8', border: '1px solid #334155', borderRadius: '8px', padding: '10px 18px', cursor: 'pointer' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, backdropFilter: 'blur(4px)' },

  // Dark ModalVer original structure
  modalCard: { background: '#13151f', borderRadius: '11px', width: '650px', maxWidth: '95vw', overflow: 'hidden', border: '1px solid #1e2130' },
  cardHeader: { background: '#0d3b5c', color: '#fff', padding: '12px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTopLeftRadius: '10px', borderTopRightRadius: '10px' },
  cardTitle: { fontSize: '18px', fontWeight: '600', textTransform: 'uppercase', color: '#fff' },
  btnCerrarWhite: { background: 'none', border: 'none', color: '#fff', fontSize: '18px', cursor: 'pointer' },
  cardBody: { padding: '30px', display: 'flex', gap: '18px', alignItems: 'flex-start' },
  avatarBox: { width: '180px', height: '220px', flexShrink: 0, border: '1px solid #1e2130', overflow: 'hidden', background: '#0f1117', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', borderRadius: '8px' },
  avatarImg: { width: '100%', height: '100%', objectFit: 'cover' },
  avatarInicialesBox: { width: '100%', height: '100%', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  avatarIniciales: { fontSize: '56px', fontWeight: '700', color: '#60a5fa' },
  cardInfo: { flex: 1, display: 'flex', flexDirection: 'column', gap: '15px' },
  infoItem: { display: 'flex', borderBottom: '1px solid #1e2130', paddingBottom: '6px' },
  infoLabel: { width: '100px', fontWeight: '700', color: '#64748b', fontSize: '15px', textAlign: 'right', marginRight: '20px' },
  infoValue: { color: '#cbd5e1', fontSize: '14.5px', fontWeight: '500' },
  cardFooter: { padding: '20px', borderTop: '1px solid #1e2130', display: 'flex', justifyContent: 'center', gap: '15px', background: '#0f1117' },
  btnAceptar: { background: '#1e2130', border: '1px solid #334155', color: '#cbd5e1', padding: '8px 30px', borderRadius: '5px', fontWeight: '600', cursor: 'pointer' },
  btnWhatsapp: { border: '1px solid #166534', color: '#4ade80', background: '#14532d', padding: '8px 30px', borderRadius: '5px', fontWeight: '700', fontSize: '12px', textDecoration: 'none', display: 'flex', alignItems: 'center' },
  modal: { background: '#13151f', border: '5px solid #1e2130', borderRadius: '16px', padding: '28px', width: '580px', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '20px' },
  modalTitulo: { color: '#f1f5f9', fontSize: '18px', fontWeight: '700' },
  btnCerrar: { background: 'none', border: 'none', color: '#94a3b8', fontSize: '18px', cursor: 'pointer' },
  fotoUploadArea: { display: 'flex', flexDirection: 'column', alignItems: 'center', marginBottom: '20px', gap: '8px' },
  fotoPreviewBox: { width: '100px', height: '100px', borderRadius: '50%', border: '2px dashed #334155', cursor: 'pointer', overflow: 'hidden', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  fotoPreviewImg: { width: '100%', height: '100%', objectFit: 'cover' },
  fotoPlaceholder: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  btnQuitarFoto: { background: 'none', border: 'none', color: '#f87171', fontSize: '12px', cursor: 'pointer' },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' },
  campoGroup: { marginTop: '1px' },
  label: { display: 'block', fontSize: '13px', color: '#94a3b8', marginBottom: '6px', fontWeight: '600' },
  input: { width: '100%', fontSize: '14px', padding: '9px 12px', background: '#0f1117', border: '1px solid #1e2130', borderRadius: '8px', color: '#e2e8f0', outline: 'none' },
  inputError: { marginTop: '6px', fontSize: '12px', color: '#f87171', lineHeight: 1.2 },
  select: { width: '100%', padding: '9px 12px', background: '#0f1117', border: '1px solid #1e2130', borderRadius: '8px', color: '#e2e8f0', outline: 'none' },
  modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '24px', borderTop: '1px solid #1e2130', paddingTop: '20px' },
  btnIcon: {
    padding: '8px',
    borderRadius: '10px',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
    background: 'rgba(255, 255, 255, 0.05)',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)', // Azul degradado
  },
}*/