
/*export const s = {
  statusActivoBg:    '#14532d',
  statusActivoText:  '#4ade80',
  statusInactivoBg:  '#450a0a',
  statusInactivoText:'#f87171',

  header:           { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  titulo:           { fontSize: '24px', fontWeight: '700', color: '#f1f5f9' },
  sub:              { fontSize: '15px', color: '#64748b', marginTop: '2px' },
  barraAcciones:    { display: 'flex', gap: '16px', marginBottom: '16px' },
  search:           { flex: 1, padding: '10px 16px', background: '#13151f', border: '1px solid #1e2130', borderRadius: '80px', color: '#e2e8f0', outline: 'none' },
  tabs:             { display: 'flex', background: '#13151f', padding: '4px', borderRadius: '10px', border: '1px solid #1e2130' },
  tab:              { padding: '8px 16px', background: 'transparent', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: '13px' },
  tabActiveVerde:   { padding: '8px 16px', background: '#14532d', border: 'none', color: '#4ade80', borderRadius: '8px', fontWeight: '600', fontSize: '13px' },
  tabActiveRojo:    { padding: '8px 16px', background: '#450a0a', border: 'none', color: '#f87171', borderRadius: '8px', fontWeight: '600', fontSize: '13px' },
  tabla:            { background: '#13151f', borderRadius: '12px', overflow: 'hidden', border: '1px solid #1e2130' },
  table:            { width: '100%', borderCollapse: 'collapse' },
  th:               { padding: '10px 16px', textAlign: 'left', fontSize: '12px', color: '#64748b', borderBottom: '1px solid #1e2130', textTransform: 'uppercase' },
  tr:               { borderBottom: '1px solid #1e2130' },
  td:               { padding: '10px 16px', fontSize: '14px', color: '#cbd5e1', verticalAlign: 'middle' },
  tdCenter:         { padding: '32px', textAlign: 'center', color: '#475569' },
  fotoTabla:        { width: '40px', height: '40px', borderRadius: '50%', objectFit: 'cover', border: '2px solid #1e2130' },
  fotoVacia:        { width: '40px', height: '40px', borderRadius: '50%', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '13px', fontWeight: '700', color: '#60a5fa' },
  nombreNom:        { fontWeight: '600', color: '#f1f5f9' },
  emailSub:         { fontSize: '12px', color: '#64748b', marginTop: '2px' },
  cinta:            { padding: '5px 12px', borderRadius: '20px', fontSize: '13px', fontWeight: '600' },
  badge:            { padding: '5px 12px', borderRadius: '20px', fontSize: '13px', fontWeight: '600' },
  acciones:         { display: 'flex', gap: '5px' },
  btnVer:           { background: '#0f172a', border: '1px solid #1e2130', borderRadius: '6px', padding: '5px 10px', cursor: 'pointer', color: '#94a3b8', fontSize: '12px' },
  btnEdit:          { background: '#1e2d4a', border: 'none', borderRadius: '6px', padding: '5px 10px', cursor: 'pointer', color: '#60a5fa', fontSize: '12px' },
  btnDel:           { background: '#2d1515', border: 'none', borderRadius: '6px', padding: '5px 10px', cursor: 'pointer', color: '#f87171', fontSize: '12px' },
  btnPrimary:       { background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 18px', fontWeight: '600', cursor: 'pointer' },
  btnSecondary:     { background: '#1e2130', color: '#94a3b8', border: '1px solid #334155', borderRadius: '8px', padding: '10px 18px', cursor: 'pointer' },
  overlay:          { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalCard:        { background: '#fff', borderRadius: '11px', width: '650px', maxWidth: '95vw', overflow: 'hidden' },
  cardHeader:       { background: '#0d3b5c', color: '#fff', padding: '12px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTopLeftRadius: '10px', borderTopRightRadius: '10px' },
  cardTitle:        { fontSize: '18px', fontWeight: '600', textTransform: 'uppercase', color: '#fff' },
  btnCerrarWhite:   { background: 'none', border: 'none', color: '#fff', fontSize: '18px', cursor: 'pointer' },
  cardBody:         { padding: '30px', display: 'flex', gap: '18px', alignItems: 'flex-start' },
  avatarBox:        { width: '180px', height: '220px', flexShrink: 0, border: '1px solid #e2e8f0', overflow: 'hidden', background: '#f8fafc', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  avatarImg:        { width: '100%', height: '100%', objectFit: 'cover' },
  avatarInicialesBox: { width: '100%', height: '100%', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  avatarIniciales:  { fontSize: '56px', fontWeight: '700', color: '#60a5fa' },
  cardInfo:         { flex: 1, display: 'flex', flexDirection: 'column', gap: '15px' },
  infoItem:         { display: 'flex', borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' },
  infoLabel:        { width: '100px', fontWeight: '700', color: '#64748b', fontSize: '15px', textAlign: 'right', marginRight: '20px' },
  infoValue:        { color: '#1e293b', fontSize: '14.5px', fontWeight: '500' },
  cardFooter:       { padding: '20px', borderTop: '1px solid #f1f5f9', display: 'flex', justifyContent: 'center', gap: '15px' },
  btnAceptar:       { background: '#fff', border: '1px solid #0d3b5c', color: '#0d3b5c', padding: '8px 30px', borderRadius: '5px', fontWeight: '600', cursor: 'pointer' },
  btnWhatsapp:      { border: '1px solid #25d366', color: '#25d366', padding: '8px 30px', borderRadius: '5px', fontWeight: '700', fontSize: '12px', textDecoration: 'none', display: 'flex', alignItems: 'center' },
  modal:            { background: '#13151f', border: '5px solid #1e2130', borderRadius: '16px', padding: '28px', width: '580px', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader:      { display: 'flex', justifyContent: 'space-between', marginBottom: '20px' },
  modalTitulo:      { color: '#f1f5f9', fontSize: '18px', fontWeight: '700' },
  btnCerrar:        { background: 'none', border: 'none', color: '#94a3b8', fontSize: '18px', cursor: 'pointer' },
  fotoUploadArea:   { display: 'flex', flexDirection: 'column', alignItems: 'center', marginBottom: '20px', gap: '8px' },
  fotoPreviewBox:   { width: '100px', height: '100px', borderRadius: '50%', border: '2px dashed #334155', cursor: 'pointer', overflow: 'hidden', background: '#1e2d4a', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  fotoPreviewImg:   { width: '100%', height: '100%', objectFit: 'cover' },
  fotoPlaceholder:  { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  btnQuitarFoto:    { background: 'none', border: 'none', color: '#f87171', fontSize: '12px', cursor: 'pointer' },
  grid2:            { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' },
  campoGroup:       { marginTop: '1px' },
  label:            { display: 'block', fontSize: '13px', color: '#94a3b8', marginBottom: '6px', fontWeight: '600' },
  input:            { width: '100%', fontSize: '14px', padding: '9px 12px', background: '#0f1117', border: '1px solid #1e2130', borderRadius: '8px', color: '#e2e8f0', outline: 'none' },
  select:           { width: '100%', padding: '9px 12px', background: '#0f1117', border: '1px solid #1e2130', borderRadius: '8px', color: '#e2e8f0', outline: 'none' },
  modalFooter:      { display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '24px', borderTop: '1px solid #1e2130', paddingTop: '20px' },
}